---
libvirt_pool_name: eci
libvirt_pool_path: /var/lib/libvirt/eci-images
libvirt_networks:
  - name: eci-nat
    cidr: 192.168.100.0/24
    forward_mode: nat
    ip: 192.168.100.1
  - name: eci-main
    cidr: 192.168.5.0/24