---
- name: config directory
  file:
    path: "{{ eci_configdir }}"
    state: directory
- name: dnsmasq config
  template:
    src: dnsmasq.conf.j2
    dest: "{{ eci_configdir }}/dnsmasq.conf"
- name: podman kube file
  template:
    src: dnsmasq.yml.j2
    dest: "{{ eci_configdir }}/dnsmasq.yml"
- name: setup tftpboot
  include_tasks: tftpboot.yml
  when: tftpboot_enabled
- name: dnsmasq service
  service:
    name: podman-kube@-etc-eci-dnsmasq.yml.service
    state: restarted
    enabled: true
