---
- name: iso directory
  file:
    path: "{{ tftpboot_iso_path }}"
    state: directory
- name: tftpboot data directory
  file:
    path: "{{ tftpboot_data }}"
    state: directory
- name: download iso
  get_url:
    url: "{{ item.url }}"
    dest: "{{ tftpboot_iso_path }}/{{ item.name }}.iso"
  loop: "{{ tftpboot_iso }}"
  when: " {{ tftpboot_download_enable }} "
  register: iso_refresh
- name: unpack iso
  containers.podman.podman_container:
    name: tftpboot-unpack
    recreate: true
    image: "{{ dnsmasq_image }}"
    volume:
      - "{{ tftpboot_iso_path }}:/data/iso:ro,z"
      - "{{ tftpboot_data }}:/tftpboot:z"
    entrypoint: "7z"
    command: "e /data/iso/{{ item.name }}.iso {{ item.files | join(' ') }} -o/tftpboot/{{ item.name }}"
  loop: "{{ tftpboot_iso }}"
  when: iso_refresh.changed
- name: ensure rootfs directory
  file:
    path: "{{ tftpboot_data }}/{{ item.name }}/{{ item.rootfs_dir }}"
    state: directory
  when: item.rootfs_dir is defined
  loop: "{{ tftpboot_iso }}"
- name: ensure rootfs
  file:
    src: "{{ tftpboot_data }}/{{ item.name }}/{{ item.rootfs }}"
    dest: "{{ tftpboot_data }}/{{ item.name }}/{{ item.rootfs_dir }}/{{ item.rootfs }}"
    state: hard
  when: item.rootfs_dir is defined
  loop: "{{ tftpboot_iso }}"
- name: ensure web server readable
  file:
    path: "{{ tftpboot_data }}/{{ item.name }}"
    state: directory
    mode: 0755
  loop: "{{ tftpboot_iso }}"
- name: generate grub
  template:
    src: grub.cfg.j2
    dest: "{{ tftpboot_data }}/{{ item.name }}/grub.cfg"
  loop: "{{ tftpboot_iso }}"