---
- name: Configure master
  community.general.nmcli:
    conn_name: "{{ item.name }}"
    ifname: "br-{{ item.name }}"
    type: bridge
    ip4: "{{ item.ip }}"
    state: present
    stp: "{{ item.stp }}"
  loop: "{{ bridges }}"
- name: Configure slave
  community.general.nmcli:
    conn_name: "{{ item.name }}-slave"
    type: bridge-slave
    ifname: "{{ item.interface }}"
    master: "br-{{ item.name }}"
    state: present
    stp: "{{ item.stp }}"
  loop: "{{ bridges }}"