---
- name: install libvirt
  package:
    name:
      - libvirt
      - virt-install
    state: present
- name: libvirt service
  service:
    name: libvirtd
    state: started
    enabled: yes
- name: setup libvirt storage
  include_tasks: storage.yml
- name: setup libvirt networks
  include_tasks: networks.yml
- name: create vms
  include_tasks: vms.yml